-- 从 nongxinle0410.sql 提取的表结构
-- 共 30 个表

CREATE TABLE `gb_distributer` (
  `gb_distributer_id` int NOT NULL AUTO_INCREMENT COMMENT '批发商id',
  `gb_distributer_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `gb_distributer_lan` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商位置经度',
  `gb_distributer_lun` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商位置纬度',
  `gb_distributer_business_type` int DEFAULT NULL COMMENT '批发商商业类型',
  `gb_distributer_manager` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_distributer_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_distributer_address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_distributer_img` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_distributer_settle_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算时间',
  `gb_distributer_settle_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算时间',
  `gb_distributer_settle_week` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算周',
  `gb_distributer_settle_month` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_distributer_settle_year` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_distributer_settle_times` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_distributer_time_quantum` tinyint DEFAULT NULL COMMENT '经营时间段',
  `gb_distributer_print_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `gb_distributer_buy_quantity` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_distributer_sys_city_id` tinyint DEFAULT NULL COMMENT '批发商商业类型',
  `gb_distributer_nx_dis_id` tinyint DEFAULT NULL COMMENT '批发商商业类型',
  `gb_distributer_pick_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `gb_distributer_record_seconds` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `gb_distributer_stock_cycle` tinyint DEFAULT NULL COMMENT '库存显示周期\n',
  PRIMARY KEY (`gb_distributer_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_department` (
  `gb_department_id` int NOT NULL AUTO_INCREMENT COMMENT '订货部门id',
  `gb_department_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门名称',
  `gb_department_father_id` int DEFAULT NULL COMMENT '订货部门上级id',
  `gb_department_type` tinyint DEFAULT NULL COMMENT '订货部门类型',
  `gb_department_sub_amount` int DEFAULT NULL COMMENT '订货部门子部门数量',
  `gb_department_dis_id` int DEFAULT NULL COMMENT '订货部门批发商id',
  `gb_department_file_path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_department_is_group_dep` tinyint DEFAULT NULL COMMENT '是客户吗',
  `gb_department_print_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_department_show_weeks` tinyint DEFAULT '1',
  `gb_department_settle_type` tinyint DEFAULT NULL,
  `gb_department_attr_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '客户简称',
  `gb_department_route_id` int DEFAULT NULL,
  `gb_department_settle_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算时间',
  `gb_department_settle_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算时间',
  `gb_department_settle_week` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算周',
  `gb_department_settle_month` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_department_settle_times` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_department_settle_year` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '结算月',
  `gb_department_dep_settle_id` int DEFAULT NULL COMMENT '结算月',
  `gb_department_level` int DEFAULT NULL COMMENT '加盟级别',
  `gb_department_sort` int DEFAULT NULL COMMENT '排序',
  `gb_department_print_set` int DEFAULT NULL COMMENT '排序',
  `gb_department_name_py` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门名称拼音',
  `gb_department_latitude` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_department_longitude` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DB_dep_father_id` int DEFAULT NULL,
  PRIMARY KEY (`gb_department_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_department_user` (
  `gb_department_user_id` int NOT NULL AUTO_INCREMENT COMMENT '订货部门用户id',
  `gb_DU_department_id` int DEFAULT NULL COMMENT '订货部门id',
  `gb_DU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信头像',
  `gb_DU_wx_nick_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信昵称',
  `gb_DU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信openid',
  `gb_DU_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信手机号码',
  `gb_DU_admin` tinyint DEFAULT NULL COMMENT '订货部门用户是否是管理员',
  `gb_DU_distributer_id` int DEFAULT NULL COMMENT '订货部门批发商id',
  `gb_DU_url_change` tinyint DEFAULT NULL,
  `gb_DU_department_father_id` int DEFAULT NULL,
  `gb_DU_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DU_print_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DU_print_bill_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DU_customer_service` int DEFAULT NULL,
  `gb_DU_login_times` int DEFAULT NULL,
  PRIMARY KEY (`gb_department_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_user` (
  `gb_distributer_user_id` int NOT NULL AUTO_INCREMENT COMMENT '批发商用户id',
  `gb_DIU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '用户名',
  `gb_DIU_wx_nick_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '登陆密码',
  `gb_DIU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DIU_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DIU_distributer_id` int DEFAULT NULL,
  `gb_DIU_admin` tinyint DEFAULT NULL,
  `gb_DIU_print_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DIU_url_change` tinyint DEFAULT NULL,
  `gb_DIU_print_bill_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DIU_qy_corp_user_id` int DEFAULT NULL COMMENT '企业用户id',
  `gb_DIU_login_times` int DEFAULT NULL COMMENT '企业用户id',
  PRIMARY KEY (`gb_distributer_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_goods` (
  `gb_distributer_goods_id` int NOT NULL AUTO_INCREMENT COMMENT '社区商品id',
  `gb_dg_dfg_goods_father_id` int DEFAULT NULL COMMENT '批发商父类商品id',
  `gb_dg_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `gb_dg_goods_status` tinyint DEFAULT NULL COMMENT '商品状态',
  `gb_dg_goods_is_weight` tinyint DEFAULT NULL COMMENT '是否称重',
  `gb_dg_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品名称',
  `gb_dg_goods_detail` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品详细',
  `gb_dg_goods_standardname` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品规格',
  `gb_dg_goods_pinyin` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '社区商品拼音',
  `gb_dg_goods_py` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '社区商品拼音简拼',
  `gb_dg_nx_goods_id` int DEFAULT NULL COMMENT 'nxGoodsId',
  `gb_dg_nx_father_img` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货方式',
  `gb_dg_nx_father_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT 'nxGoodsFatherId',
  `gb_dg_nx_grand_id` int DEFAULT NULL COMMENT 'nxGoodsGrandid',
  `gb_dg_nx_great_grand_id` int DEFAULT NULL COMMENT 'nxGreatGrandid',
  `gb_dg_pull_off` tinyint DEFAULT NULL COMMENT '是否下架',
  `gb_dg_goods_brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_goods_place` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_nx_goods_father_color` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_goods_standard_weight` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_goods_type` tinyint DEFAULT NULL COMMENT '1 集采 2出库 3 自采',
  `gb_dg_goods_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '价格',
  `gb_dg_goods_lowest_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_goods_highest_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_nx_distributer_id` int DEFAULT NULL COMMENT '商品库父类id',
  `gb_dg_nx_distributer_goods_id` int DEFAULT NULL,
  `gb_dg_gb_department_id` int DEFAULT NULL COMMENT '库房或中央厨房id',
  `gb_dg_control_price` tinyint DEFAULT NULL COMMENT '是否控制价格',
  `gb_dg_control_fresh` tinyint DEFAULT NULL COMMENT '是否控制鲜度',
  `gb_dg_fresh_warn_hour` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '鲜度报警小时',
  `gb_dg_fresh_waste_hour` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '废弃报警小时',
  `gb_dg_goods_inventory_type` tinyint DEFAULT NULL COMMENT '盘库方式1 月，2周，3日',
  `gb_dg_gb_supplier_id` int DEFAULT NULL COMMENT '指定供货商id',
  `gb_dg_franchise_price_one` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_franchise_price_two` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_franchise_price_three` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_franchise_price_one_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_franchise_price_two_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_franchise_price_three_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_is_franchise_price` int DEFAULT NULL COMMENT '加盟商商品',
  `gb_dg_is_self_control` int DEFAULT NULL COMMENT '自制商品',
  `gb_dg_self_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '自制价格',
  `gb_dg_selling_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '销售价格',
  `gb_dg_goods_sort` int DEFAULT NULL COMMENT '商品状态',
  `gb_dg_goods_sons_sort` int DEFAULT NULL COMMENT '子商品顺序',
  `gb_dg_goods_is_hidden` int DEFAULT NULL COMMENT '是否显示',
  `gb_dg_nx_father_img_large` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货方式',
  `gb_dg_nx_distributer_goods_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dg_dfg_goods_grand_id` int DEFAULT NULL COMMENT '批发商父类商品id',
  `gb_dg_dfg_goods_great_id` int DEFAULT NULL COMMENT '批发商父类商品id',
  `gb_dg_quantity_days` int DEFAULT NULL COMMENT '批发商父类商品id',
  PRIMARY KEY (`gb_distributer_goods_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_department_orders` (
  `gb_department_orders_id` int NOT NULL AUTO_INCREMENT COMMENT '部门订单id',
  `gb_DO_nx_goods_id` int DEFAULT NULL COMMENT '部门订单nx商品id',
  `gb_DO_nx_goods_father_id` int DEFAULT NULL COMMENT '部门订单商品父id',
  `gb_DO_dis_goods_id` int DEFAULT NULL COMMENT '部门订单社区商品id',
  `gb_DO_dis_goods_father_id` int DEFAULT NULL COMMENT '批发商父级商品id',
  `gb_DO_dep_dis_goods_id` int DEFAULT NULL,
  `gb_DO_quantity` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请数量',
  `gb_DO_standard` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请规格',
  `gb_DO_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请备注',
  `gb_DO_weight` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单重量',
  `gb_DO_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单商品单价',
  `gb_DO_subtotal` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请商品小计',
  `gb_DO_department_id` int DEFAULT NULL COMMENT '部门订单部门id',
  `gb_DO_department_father_id` int DEFAULT NULL,
  `gb_DO_distributer_id` int DEFAULT NULL COMMENT '部门订单批发商id',
  `gb_DO_purchase_user_id` int DEFAULT NULL COMMENT '部门商品采购员id',
  `gb_DO_bill_id` int DEFAULT NULL COMMENT '部门订单账单id',
  `gb_DO_status` tinyint DEFAULT NULL COMMENT '部门订单申请商品状态',
  `gb_DO_order_user_id` int DEFAULT NULL COMMENT '部门订单订货用户id',
  `gb_DO_pick_user_id` int DEFAULT NULL COMMENT '部门订单商品称重用户id',
  `gb_DO_receive_user_id` int DEFAULT NULL COMMENT '收货用户id',
  `gb_DO_buy_status` tinyint DEFAULT NULL COMMENT '部门订单商品进货状态',
  `gb_DO_purchase_goods_id` int DEFAULT NULL COMMENT '订单采购商品id',
  `gb_DO_apply_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请时间',
  `gb_DO_apply_what_day` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请星期',
  `gb_DO_apply_arrive_date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单申请时间',
  `gb_DO_apply_full_time` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DO_apply_only_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DO_arrive_only_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DO_arrive_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单送达时间',
  `gb_DO_arrive_weeks_year` int DEFAULT NULL COMMENT '本年第几周',
  `gb_DO_arrive_what_day` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '星期几',
  `gb_DO_goods_type` tinyint DEFAULT NULL COMMENT '配送商品0，自采购商品1',
  `gb_DO_operation_time` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DO_is_agent` tinyint DEFAULT NULL,
  `gb_DO_cost_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货单价',
  `gb_DO_cost_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货重量',
  `gb_DO_cost_subtotal` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货小计',
  `gb_DO_nx_distributer_id` int DEFAULT NULL COMMENT 'comGoods的批发商商品id',
  `gb_DO_nx_distributer_goods_id` int DEFAULT NULL COMMENT 'comGoods的批发商',
  `gb_DO_dg_goods_sell_type` tinyint DEFAULT NULL COMMENT '按规格销售方式',
  `gb_DO_nx_department_order_id` int DEFAULT NULL COMMENT 'nxDepartmentId',
  `gb_DO_to_department_id` int DEFAULT NULL COMMENT '库房或者中央厨房部门id',
  `gb_DO_order_type` tinyint DEFAULT NULL COMMENT '订单类型',
  `gb_DO_return_user_id` int DEFAULT NULL COMMENT '库房或者中央厨房部门id',
  `gb_DO_ds_standard_id` int DEFAULT NULL COMMENT '订货单位id',
  `gb_DO_ds_standard_scale` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货单位比例',
  `gb_DO_scale_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单重量',
  `gb_DO_scale_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '部门订单重量',
  `gb_DO_weight_total_id` int DEFAULT NULL COMMENT '拣货单id',
  `gb_DO_selling_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '零售单价',
  `gb_DO_selling_subtotal` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '零售小计',
  `gb_DO_weight_goods_id` int DEFAULT NULL COMMENT 'id',
  `gb_DO_price_different` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT 'id',
  `gb_DO_dgsr_return_id` int DEFAULT NULL COMMENT '库房或者中央厨房部门id',
  `gb_DO_dis_goods_grand_id` int DEFAULT NULL COMMENT '批发商父级商品id',
  `gb_DO_nx_goods_grand_id` int DEFAULT NULL COMMENT '批发商父级商品id',
  `gb_DO_nx_goods_great_id` int DEFAULT NULL COMMENT '批发商父级商品id',
  `gb_DO_print_standard` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT 'id',
  `gb_DO_cost_price_level` int DEFAULT NULL COMMENT '批发商父级商品id',
  `gb_DO_goods_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品名称',
  `gb_DO_dis_goods_great_id` int DEFAULT NULL COMMENT '批发商父级商品id',
  PRIMARY KEY (`gb_department_orders_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_department_dis_goods` (
  `gb_department_dis_goods_id` int NOT NULL AUTO_INCREMENT,
  `gb_DDG_department_father_id` int DEFAULT NULL,
  `gb_DDG_department_id` int DEFAULT NULL,
  `gb_DDG_dis_goods_id` int DEFAULT NULL,
  `gb_DDG_dis_goods_father_id` int DEFAULT NULL,
  `gb_DDG_dep_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_pinyin` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_py` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_standardname` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_detail` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_dep_goods_place` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_gb_department_id` int DEFAULT NULL COMMENT '库房或中央厨房id',
  `gb_DDG_goods_type` tinyint DEFAULT NULL,
  `gb_DDG_nx_distributer_id` int DEFAULT NULL COMMENT '商品库父类id',
  `gb_DDG_nx_distributer_goods_id` int DEFAULT NULL,
  `gb_DDG_inventory_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_inventory_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_stock_total_weight` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_stock_total_subtotal` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_gb_supplier_id` int DEFAULT NULL COMMENT '指定供货商id',
  `gb_DDG_prepare_total_weight` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_show_standard_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_show_standard_id` int DEFAULT NULL,
  `gb_DDG_show_standard_scale` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_level_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '加盟级别商品价格',
  `gb_DDG_prepare_status` int DEFAULT NULL,
  `gb_DDG_selling_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '加盟级别商品价格',
  `gb_DDG_show_standard_weight` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_quantity` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_standard` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_print_standard` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_gb_dis_id` int DEFAULT NULL,
  `gb_DDG_dep_goods_pull_off` int DEFAULT NULL,
  `gb_DDG_dep_goods_status` int DEFAULT NULL,
  `gb_DDG_dis_goods_grand_id` int DEFAULT NULL,
  `gb_DDG_dis_goods_great_id` int DEFAULT NULL,
  `gb_DDG_order_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DDG_order_price_level` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`gb_department_dis_goods_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_father_goods` (
  `gb_distributer_father_goods_id` int NOT NULL AUTO_INCREMENT,
  `gb_dfg_father_goods_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dfg_father_goods_img` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dfg_father_goods_sort` int DEFAULT NULL,
  `gb_dfg_father_goods_color` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_dfg_fathers_father_id` int DEFAULT NULL,
  `gb_dfg_father_goods_level` tinyint DEFAULT NULL,
  `gb_dfg_distributer_id` int DEFAULT NULL,
  `gb_dfg_goods_amount` int DEFAULT NULL,
  `gb_dfg_nx_goods_id` int DEFAULT NULL,
  `gb_dfg_price_amount` int DEFAULT NULL,
  `gb_dfg_price_two_amount` int DEFAULT NULL,
  `gb_dfg_price_three_amount` int DEFAULT NULL,
  `gb_dfg_father_goods_img_large` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`gb_distributer_father_goods_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_standard` (
  `gb_distributer_standard_id` int NOT NULL AUTO_INCREMENT,
  `gb_DS_dis_goods_id` int DEFAULT NULL,
  `gb_DS_standard_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DS_standard_file_path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DS_standard_scale` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DS_standard_error` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DS_standard_sort` int DEFAULT NULL,
  `gb_DS_standard_weight` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`gb_distributer_standard_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_pay` (
  `gb_distributer_pay_id` int NOT NULL AUTO_INCREMENT,
  `gb_gdp_gb_dis_id` int DEFAULT NULL,
  `gb_gdp_pay_subtotal` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_gdp_from_time` date DEFAULT NULL,
  `gb_gdp_stop_time` date DEFAULT NULL,
  `gb_gdp_pay_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_gdp_type` tinyint DEFAULT NULL,
  `gb_gdp_status` tinyint DEFAULT NULL,
  `gb_gdp_trade_no` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_gdp_gb_new_dis_id` int DEFAULT NULL,
  `gb_gdp_buy_quantity` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_gdp_img_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_gdp_sell_detail` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`gb_distributer_pay_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_module` (
  `gb_distributer_module_id` int NOT NULL AUTO_INCREMENT,
  `gb_dm_fixed_supplier_number` int DEFAULT '-1',
  `gb_dm_purchase_number` int DEFAULT '-1',
  `gb_dm_stock_number` int DEFAULT '-1',
  `gb_dm_app_supplier_number` int DEFAULT '-1',
  `gb_dm_central_kitchen_number` int DEFAULT '-1',
  `gb_dm_direct_sales_number` int DEFAULT '-1',
  `gb_dm_franchisee_number` int DEFAULT '-1',
  `gb_dm_distributer_id` int NOT NULL DEFAULT '-1',
  PRIMARY KEY (`gb_distributer_module_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `gb_distributer_purchase_batch` (
  `gb_distributer_purchase_batch_id` int NOT NULL AUTO_INCREMENT COMMENT '批发商进货批次id',
  `gb_DPB_status` tinyint DEFAULT NULL COMMENT '批发商进货批次状态',
  `gb_DPB_user_admin_type` tinyint DEFAULT NULL COMMENT '进货批次用户类型',
  `gb_DPB_time` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商进货批次时间',
  `gb_DPB_pur_user_id` int DEFAULT NULL COMMENT '批发商进货采购员id',
  `gb_DPB_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `gb_DPB_date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_hour` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_minute` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_subtotal` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_pur_department_id` int DEFAULT NULL COMMENT '采购部门id',
  `gb_DPB_pay_type` int DEFAULT NULL COMMENT '付款方式:0==现金; 1 ==记账，',
  `gb_DPB_pay_subtotal` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '付款金额',
  `gb_DPB_supplier_id` int DEFAULT NULL COMMENT '供货商商id',
  `gb_DPB_purchase_month` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_purchase_year` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_purchase_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_gb_supplier_payment_id` int DEFAULT NULL,
  `gb_DPB_purchase_week` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_seller_reply_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_finish_full_time` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_nx_distributer_id` int DEFAULT NULL COMMENT '供货商商id',
  `gb_DPB_buy_user_id` int DEFAULT NULL COMMENT '供货商商id',
  `gb_DPB_sell_user_id` int DEFAULT NULL COMMENT '供货商商id',
  `gb_DPB_buy_user_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_sell_user_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `gb_DPB_purchase_type` tinyint DEFAULT NULL COMMENT '0 手动订货，1 自动订货',
  `gb_DPB_dep_bill_id` int DEFAULT NULL COMMENT '供货商商id',
  PRIMARY KEY (`gb_distributer_purchase_batch_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_distributer_gb_distributer` (
  `nx_distributer_gb_distributer_id` int NOT NULL AUTO_INCREMENT,
  `nx_DGD_nx_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_DGD_gb_distributer_id` int DEFAULT NULL COMMENT '客户id',
  `nx_DGD_gb_dep_id` int DEFAULT NULL,
  `nx_DGD_gb_dep_user_id` int DEFAULT NULL,
  `nx_DGD_gb_pay_method` tinyint DEFAULT NULL COMMENT '付款方式0现金1记账',
  `nx_DGD_gb_goods_price` tinyint DEFAULT NULL COMMENT '商品定价方式0随行就市1固定',
  `nx_DGD_status` tinyint DEFAULT NULL COMMENT '-1 请求 0 通过',
  `nx_DGD_gb_pay_period_week` tinyint DEFAULT NULL COMMENT '付款方式0现金1记账',
  `nx_DGD_from_nx_dep_id` int DEFAULT NULL,
  `nx_DGD_nx_supplier_id` int DEFAULT NULL,
  `nx_DGD_from_nx_dis_id` int DEFAULT NULL,
  PRIMARY KEY (`nx_distributer_gb_distributer_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_distributer` (
  `nx_distributer_id` int NOT NULL AUTO_INCREMENT COMMENT '批发商id',
  `nx_distributer_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `nx_distributer_lan` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商位置经度',
  `nx_distributer_lun` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商位置纬度',
  `nx_distributer_business_type_id` tinyint DEFAULT NULL COMMENT '批发商商业类型',
  `nx_distributer_manager` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_img` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_market_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_type` tinyint DEFAULT NULL COMMENT '批发商商业类型',
  `nx_distributer_app_id` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_buy_quantity` varchar(100) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_shelf_quantity` int DEFAULT NULL,
  `nx_distributer_pay_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_distributer_sys_market_id` int DEFAULT NULL COMMENT '批发商商业类型',
  `nx_distributer_sys_city_id` tinyint DEFAULT NULL COMMENT '批发商商业类型',
  `nx_distributer_show_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商名称',
  `invited_by_nx_distributer_id` int DEFAULT NULL COMMENT '邀请我注册的配送商id',
  `invite_code` varchar(16) COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '我的邀请码(用于生成邀请链接)',
  PRIMARY KEY (`nx_distributer_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=172 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_distributer_user` (
  `nx_distributer_user_id` int NOT NULL AUTO_INCREMENT COMMENT '批发商用户id',
  `nx_DIU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '用户名',
  `nx_DIU_wx_nick_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '登陆密码',
  `nx_DIU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DIU_wx_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DIU_distributer_id` int DEFAULT NULL,
  `nx_DIU_admin` tinyint DEFAULT NULL,
  `nx_DIU_print_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DIU_url_change` tinyint DEFAULT NULL,
  `nx_DIU_print_bill_device_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DIU_role_id` tinyint DEFAULT NULL COMMENT '用户角色 1,拣货员;2,打包员;3,司机;',
  `nx_DIU_qy_corp_user_id` int DEFAULT NULL COMMENT '企业用户id',
  `nx_DIU_login_times` int DEFAULT NULL COMMENT '企业用户id',
  `nx_DIU_login_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`nx_distributer_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=305 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_distributer_goods` (
  `nx_distributer_goods_id` int NOT NULL AUTO_INCREMENT COMMENT '社区商品id',
  `nx_dg_dfg_goods_father_id` int DEFAULT NULL COMMENT '批发商父类商品id',
  `nx_dg_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_dg_goods_status` tinyint DEFAULT NULL COMMENT '商品状态',
  `nx_dg_goods_is_weight` tinyint DEFAULT NULL COMMENT '是否称重',
  `nx_dg_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品名称',
  `nx_dg_goods_detail` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品详细',
  `nx_dg_goods_standardname` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品规格',
  `nx_dg_goods_pinyin` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '社区商品拼音',
  `nx_dg_goods_py` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '社区商品拼音简拼',
  `nx_dg_nx_goods_id` int DEFAULT NULL COMMENT 'nxGoodsId',
  `nx_dg_nx_father_img` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '进货方式',
  `nx_dg_nx_father_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT 'nxGoodsFatherId',
  `nx_dg_nx_grand_id` int DEFAULT NULL COMMENT 'nxGoodsGrandid',
  `nx_dg_nx_great_grand_id` int DEFAULT NULL COMMENT 'nxGreatGrandid',
  `nx_dg_pull_off` tinyint DEFAULT NULL COMMENT '是否下架',
  `nx_dg_goods_brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_goods_place` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_nx_goods_father_color` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_goods_standard_weight` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_purchase_auto` int DEFAULT NULL,
  `nx_dg_supplier_id` int DEFAULT NULL,
  `nx_dg_buying_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_one` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_two` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_three` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_one_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_two_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_profit_three_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_one` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_two` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_three` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_one_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_two_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_three_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_buying_price_is_grade` tinyint DEFAULT NULL,
  `nx_dg_goods_file` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_dfg_goods_grand_id` int DEFAULT NULL COMMENT '批发商父类商品id',
  `nx_dg_is_oldest_son` int DEFAULT NULL COMMENT '批发商父类商品id',
  `nx_dg_price_first_day` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_second_day` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_price_third_day` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_goods_sort` int DEFAULT NULL COMMENT '商品状态',
  `nx_dg_goods_sons_sort` int DEFAULT NULL COMMENT '商品状态',
  `nx_dg_goods_is_hidden` int DEFAULT NULL COMMENT '商品状态',
  `nx_dg_trace_report_id` int DEFAULT NULL COMMENT '溯源报告ID',
  `nx_dg_will_price_update` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_goods_file_large` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_one` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_two` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_three` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_one_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_two_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_three_weight` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_out_total_weight` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_one_standard` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_two_standard` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_three_standard` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_one_about_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_two_about_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_will_price_three_about_price` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_dg_quantity_days` int DEFAULT NULL COMMENT '商品状态',
  `nx_dg_carton_unit` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '外箱名称',
  `nx_dg_items_per_carton` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`nx_distributer_goods_id`) USING BTREE,
  KEY `idx_trace_report_id` (`nx_dg_trace_report_id`)
) ENGINE=InnoDB AUTO_INCREMENT=39548 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_distributer_standard` (
  `nx_distributer_standard_id` int NOT NULL AUTO_INCREMENT,
  `nx_DS_dis_goods_id` int DEFAULT NULL,
  `nx_DS_standard_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DS_standard_file_path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DS_standard_scale` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DS_standard_error` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DS_standard_sort` int DEFAULT NULL,
  `nx_DS_standard_weight` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`nx_distributer_standard_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5145 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_department` (
  `nx_department_id` int NOT NULL AUTO_INCREMENT COMMENT '订货部门id',
  `nx_department_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门名称',
  `nx_department_app_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_father_id` int DEFAULT NULL COMMENT '订货部门上级id',
  `nx_department_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门类型',
  `nx_department_sub_amount` int DEFAULT NULL COMMENT '订货部门子部门数量',
  `nx_department_dis_id` int DEFAULT NULL COMMENT '订货部门批发商id',
  `nx_department_file_path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_is_group_dep` tinyint DEFAULT NULL COMMENT '是客户吗',
  `nx_department_print_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_show_weeks` tinyint DEFAULT '1',
  `nx_department_settle_type` tinyint DEFAULT NULL,
  `nx_department_attr_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '客户简称',
  `nx_department_pick_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '客户简称',
  `nx_department_driver_id` int DEFAULT NULL,
  `nx_department_owe_box_number` int DEFAULT '0',
  `nx_department_delivery_box_number` int DEFAULT '0',
  `nx_department_working_status` int DEFAULT NULL,
  `nx_department_unPay_total` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_add_count` int DEFAULT NULL,
  `nx_department_pay_total` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_profit_total` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_promotion_goods_id` int DEFAULT NULL,
  `nx_department_join_date` varchar(10) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_order_total` bigint DEFAULT NULL,
  `nx_department_pinyin` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_lat` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_lng` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_record_minutes` int DEFAULT NULL,
  `nx_department_earliest_delivery_time` int DEFAULT NULL COMMENT '最早配送时间（秒）',
  `nx_department_latest_delivery_time` int DEFAULT NULL COMMENT '最晚配送时间（秒）',
  `nx_department_address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_department_unload_duration` int DEFAULT NULL,
  `nx_department_gb_distributer_id` int DEFAULT NULL,
  `nx_department_points` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT '0' COMMENT '部门积分',
  `nx_department_waiting_points` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT '0' COMMENT '等待积分（客户货品卖出前的积分，卖出后加到积分字段）',
  `nx_department_ocr_prompt_image` text COLLATE utf8mb4_czech_ci COMMENT 'OCR修正指令-图片上传（用于存储用户的修正要求，针对图片识别）',
  `nx_department_ocr_prompt_excel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci COMMENT 'OCR修正指令累计（用于存储用户的修正要求，累计到部门级别）',
  `nx_department_ocr_prompt_paste` text COLLATE utf8mb4_czech_ci COMMENT 'OCR修正指令-复制粘贴（用于存储用户的修正要求，针对粘贴识别）',
  `nx_department_order_code` varchar(255) COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货代号（用于对客户名称保密）',
  PRIMARY KEY (`nx_department_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1510 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_department_user` (
  `nx_department_user_id` int NOT NULL AUTO_INCREMENT COMMENT '订货部门用户id',
  `nx_DU_department_id` int DEFAULT NULL COMMENT '订货部门id',
  `nx_DU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信头像',
  `nx_DU_wx_nick_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信昵称',
  `nx_DU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信openid',
  `nx_DU_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货部门用户微信手机号码',
  `nx_DU_admin` tinyint DEFAULT NULL COMMENT '订货部门用户是否是管理员',
  `nx_DU_distributer_id` int DEFAULT NULL COMMENT '订货部门批发商id',
  `nx_DU_url_change` tinyint DEFAULT NULL,
  `nx_DU_department_father_id` int DEFAULT NULL,
  `nx_DU_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DU_login_times` int DEFAULT NULL,
  `nx_DU_login_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '机器登录码',
  PRIMARY KEY (`nx_department_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=259 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_department_bill` (
  `nx_department_bill_id` int NOT NULL AUTO_INCREMENT,
  `nx_DB_dis_id` int DEFAULT NULL,
  `nx_DB_dep_id` int DEFAULT NULL,
  `nx_DB_total` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_status` tinyint DEFAULT NULL,
  `nx_DB_time` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_issue_user_id` int DEFAULT NULL,
  `nx_DB_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_month` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_week` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_trade_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_print_times` int DEFAULT NULL,
  `nx_DB_day` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '星期',
  `nx_DB_gb_dis_id` int DEFAULT NULL,
  `nx_DB_gb_dep_id` int DEFAULT NULL,
  `nx_DB_profit_total` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_profit_scale` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_nx_community_id` int DEFAULT NULL,
  `nx_DB_nx_restraunt_id` int DEFAULT NULL,
  `nx_DB_pay_points` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT '0' COMMENT '支付积分',
  `nx_DB_pay_cash` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT '0' COMMENT '支付现金',
  `nx_DB_cost_total` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_dep_father_id` int DEFAULT NULL,
  `nx_DB_wx_out_trade_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_year` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DB_gb_department_bill_id` int DEFAULT NULL,
  `nx_DB_gb_dep_father_id` int DEFAULT NULL,
  PRIMARY KEY (`nx_department_bill_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10270 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_department_dis_goods` (
  `nx_department_dis_goods_id` int NOT NULL AUTO_INCREMENT,
  `nx_DDG_department_father_id` int DEFAULT NULL,
  `nx_DDG_department_id` int DEFAULT NULL,
  `nx_DDG_dis_goods_id` int DEFAULT NULL,
  `nx_DDG_dis_goods_father_id` int DEFAULT NULL,
  `nx_DDG_dep_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_pinyin` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_py` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_standardname` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_detail` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_dep_goods_place` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_quantity` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_standard` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_is_gb_department` tinyint DEFAULT NULL,
  `nx_DDG_gb_department_father_id` int DEFAULT NULL,
  `nx_DDG_gb_department_id` int DEFAULT NULL,
  `nx_DDG_order_cost_price` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_order_seller_user_id` int DEFAULT NULL,
  `nx_DDG_order_buyer_user_id` int DEFAULT NULL,
  `nx_DDG_dis_goods_grand_id` int DEFAULT NULL,
  `nx_DDG_dis_goods_great_id` int DEFAULT NULL,
  `nx_DDG_order_goods_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_pick_detail` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_nx_distributer_id` int DEFAULT NULL,
  `nx_DDG_gb_distributer_id` int DEFAULT NULL,
  `nx_DDG_order_price_level` varchar(10) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_DDG_goods_nx_distributer_id` int DEFAULT NULL,
  PRIMARY KEY (`nx_department_dis_goods_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=14346 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_buy_user` (
  `nx_buy_user_id` int NOT NULL AUTO_INCREMENT COMMENT '订货用户id',
  `nx_BU_retailer_id` int DEFAULT NULL COMMENT '零售商id',
  `nx_BU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信头像',
  `nx_BU_wx_nick_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信昵称',
  `nx_BU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信openid',
  `nx_BU_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货户微信手机号码',
  `nx_BU_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '零售商用户加入日期',
  `nx_BU_nx_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_BU_nx_dis_user_id` int DEFAULT NULL COMMENT '批发商用户id',
  PRIMARY KEY (`nx_buy_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_sell_user` (
  `nx_sell_user_id` int NOT NULL AUTO_INCREMENT COMMENT '卖货用户id',
  `nx_SU_retailer_id` int DEFAULT NULL COMMENT '零售商id',
  `nx_SU_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '卖货用户微信头像',
  `nx_SU_wx_nick_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '卖货用户微信昵称',
  `nx_SU_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '卖货用户微信openid',
  `nx_SU_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '卖货户微信手机号码',
  `nx_SU_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '用户加入日期',
  `nx_SU_gb_dis_supplier_id` int DEFAULT NULL COMMENT 'gb供货商id',
  `nx_SU_nx_dis_id` int DEFAULT NULL COMMENT 'nxDistributerId',
  PRIMARY KEY (`nx_sell_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_goods` (
  `nx_goods_id` int NOT NULL AUTO_INCREMENT COMMENT '商品id',
  `nx_goods_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品名称',
  `nx_goods_standardname` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品规格',
  `nx_goods_detail` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品描述',
  `nx_goods_brand` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品品牌',
  `nx_goods_place` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '商品产地',
  `nx_goods_pinyin` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '拼音',
  `nx_goods_py` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '简拼',
  `nx_goods_father_id` int DEFAULT NULL COMMENT '父级id',
  `nx_goods_sort` int DEFAULT NULL COMMENT '商品排序',
  `nx_goods_file` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '图片',
  `nx_goods_standard_amount` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '销售规格数量',
  `nx_goods_standard_weight` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `nx_goods_apply_nx_distributer_id` int DEFAULT NULL COMMENT '申请批发商id',
  `nx_goods_level` int DEFAULT NULL COMMENT '申请批发商id',
  `nx_goods_grand_id` int DEFAULT NULL COMMENT '父级id',
  `nx_goods_is_oldest_son` int DEFAULT NULL COMMENT '父级id',
  `nx_goods_sons_sort` int DEFAULT NULL COMMENT '父级id',
  `nx_goods_is_hidden` int DEFAULT NULL COMMENT '父级id',
  `nx_goods_file_big` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '图片',
  `nx_goods_great_grand_id` int DEFAULT NULL COMMENT '以级id',
  `nx_goods_quantity_days` int DEFAULT NULL COMMENT '保鲜天数',
  `nx_goods_carton_unit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '外箱名称',
  `nx_goods_items_per_carton` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`nx_goods_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=106289 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_jrdh_user` (
  `nx_jrdh_user_id` int NOT NULL AUTO_INCREMENT COMMENT '订货用户id',
  `nx_jrdh_wx_avartra_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信头像',
  `nx_jrdh_wx_nick_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信昵称',
  `nx_jrdh_wx_open_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货用户微信openid',
  `nx_jrdh_wx_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '订货户微信手机号码',
  `nx_jrdh_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '零售商用户加入日期',
  `nx_jrdh_nx_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_jrdh_nx_purchaser_user_id` int DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_nx_community_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_jrdh_nx_comm_purchaser_user_id` int DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_url_change` int DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_admin` int DEFAULT NULL COMMENT '0 seller, 1nxpurchaser 2 gbpurchaser ',
  `nx_jrdh_gb_distributer_id` int DEFAULT NULL COMMENT '批发商id',
  `nx_jrdh_gb_department_id` int DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_gb_department_user_id` int DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_device_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_device_print_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '批发商用户id',
  `nx_jrdh_auth_supplier_id` int DEFAULT NULL COMMENT '批发商id',
  PRIMARY KEY (`nx_jrdh_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `nx_jrdh_supplier` (
  `nx_jrdh_supplier_id` int NOT NULL AUTO_INCREMENT COMMENT '供货商id',
  `nx_jrdhs_supplier_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '供货商名称',
  `nx_jrdhs_gb_distributer_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_gb_department_id` int DEFAULT NULL COMMENT 'gbDepid',
  `nx_jrdhs_user_id` int DEFAULT NULL COMMENT '接单元id',
  `nx_jrdhs_nx_distributer_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_nx_community_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_nx_pur_user_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_gb_pur_user_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_comm_pur_user_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_nx_jrdh_buy_user_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_status` tinyint(1) DEFAULT NULL COMMENT '供货商名称',
  `nx_jrdhs_sys_city_id` int DEFAULT NULL COMMENT 'gbDisid',
  `nx_jrdhs_sys_market_id` int DEFAULT NULL COMMENT 'gbDisid',
  PRIMARY KEY (`nx_jrdh_supplier_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `sys_city_market` (
  `sys_city_market_id` int NOT NULL AUTO_INCREMENT,
  `sys_cm_city_id` int DEFAULT NULL,
  `sys_cm_market_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `sys_cm_machine_agent_id` int DEFAULT NULL,
  `sys_cm_register_gift_points` int DEFAULT '1000' COMMENT '配送商注册赠送试用点数',
  `sys_cm_points_per_yuan` int DEFAULT '100' COMMENT '一元兑换点数比例',
  `sys_cm_self_print_enabled` tinyint(1) DEFAULT '0' COMMENT '是否开通自助打印机器：0=关闭，1=开启',
  `sys_cm_manager_phone` varchar(20) COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '市场管理人员手机号',
  `sys_cm_area_coordinates` text COLLATE utf8mb4_czech_ci COMMENT '市场区域范围坐标（JSON格式存储多边形坐标点）',
  `sys_cm_center_latitude` decimal(10,7) DEFAULT NULL COMMENT '市场中心点纬度',
  `sys_cm_center_longitude` decimal(10,7) DEFAULT NULL COMMENT '市场中心点经度',
  `sys_cm_delivery_radius` int DEFAULT '5000' COMMENT '市场配送半径（米），默认5公里',
  `sys_cm_pay_config_class` varchar(100) COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '市场支付配置类名（如：MyWxJjdhPayConfig）',
  `sys_cm_mini_app_id` varchar(50) COLLATE utf8mb4_czech_ci DEFAULT NULL COMMENT '市场小程序AppID（如：wx58ba279bc3d04c4a）',
  PRIMARY KEY (`sys_city_market_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `sys_business_type` (
  `sys_business_type_id` int NOT NULL,
  `sys_business_type_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `sys_by_dis_type` tinyint DEFAULT NULL COMMENT 'nxDis 1, gbDis 2,',
  PRIMARY KEY (`sys_business_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;

CREATE TABLE `sys_user` (
  `user_id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(100) DEFAULT NULL COMMENT '密码',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `mobile` varchar(100) DEFAULT NULL COMMENT '手机号',
  `status` tinyint DEFAULT NULL COMMENT '状态  0：禁用   1：正常',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `user_dis_user_id` int DEFAULT NULL,
  `user_dis_id` int DEFAULT NULL,
  PRIMARY KEY (`user_id`) USING BTREE,
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=428 DEFAULT CHARSET=utf8mb3 COMMENT='系统用户';

CREATE TABLE `qy_gb_dis_corp_user` (
  `qy_gb_dis_corp_user_id` int NOT NULL AUTO_INCREMENT,
  `qy_gb_dis_corp_user_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `qy_gb_dis_corp_user_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `qy_gb_dis_corp_open_user_id` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `qy_gb_dis_corp_qy_corp_id` int DEFAULT NULL,
  `qy_gb_distributer_id` int DEFAULT NULL,
  `qy_gb_dis_corp_session_key` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  `qy_gb_dis_corp_user_join_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci DEFAULT NULL,
  PRIMARY KEY (`qy_gb_dis_corp_user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_czech_ci;
