/*
 Navicat Premium Data Transfer

 Source Server         : gpt
 Source Server Type    : MySQL
 Source Server Version : 80027 (8.0.27-0ubuntu0.20.04.1)
 Source Host           : localhost:3306
 Source Schema         : nongxinle

 Target Server Type    : MySQL
 Target Server Version : 80027 (8.0.27-0ubuntu0.20.04.1)
 File Encoding         : 65001

 Date: 11/04/2026 12:04:58
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for nx_standard
-- ----------------------------
DROP TABLE IF EXISTS `nx_standard`;
CREATE TABLE `nx_standard` (
  `nx_standard_id` int NOT NULL AUTO_INCREMENT,
  `nx_standard_name` varchar(10) CHARACTER SET utf16 COLLATE utf16_czech_ci DEFAULT NULL,
  `nx_s_goods_id` int DEFAULT NULL,
  `nx_standard_file_path` varchar(200) CHARACTER SET utf16 COLLATE utf16_czech_ci DEFAULT NULL,
  `nx_standard_scale` varchar(10) CHARACTER SET utf16 COLLATE utf16_czech_ci DEFAULT NULL,
  `nx_standard_error` varchar(10) CHARACTER SET utf16 COLLATE utf16_czech_ci DEFAULT NULL,
  `nx_standard_sort` int DEFAULT NULL,
  `nx_standard_weight` varchar(200) CHARACTER SET utf16 COLLATE utf16_czech_ci DEFAULT NULL,
  PRIMARY KEY (`nx_standard_id`)
) ENGINE=InnoDB AUTO_INCREMENT=477 DEFAULT CHARSET=utf16 COLLATE=utf16_czech_ci;

-- ----------------------------
-- Records of nx_standard
-- ----------------------------
BEGIN;
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (1, '根', 45096, 'uploadImage/wxbc686226ccc443f1.o6zAJsw3k3_I4jY0lYtqK1TqmM_c.0r30bxBpTNcFbabac3529edec5e2c86ba0c548932af5.jpg', '1.3', '0', NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (158, '个', 45559, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (159, '箱', 45506, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (160, '个', 45126, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (161, '个', 45580, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (162, '根', 45114, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (164, '把', 45176, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (165, '捆', 45174, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (166, '把', 45198, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (167, '颗', 45188, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (168, '把', 45189, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (169, '把', 45191, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (170, '个', 45563, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (171, '颗', 45182, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (172, '个', 45106, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (173, '根', 45094, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (174, '个', 45139, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (180, '个', 45217, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (181, '个', 45247, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (182, '个', 45258, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (183, '个', 45239, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (184, '个', 45284, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (185, '个', 45285, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (186, '个', 45286, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (187, '个', 45237, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (188, '个', 45236, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (189, '个', 45226, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (190, '个', 45225, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (191, '个', 45272, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (192, '个', 45265, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (193, '个', 45288, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (194, '个', 45243, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (195, '个', 45240, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (196, '个', 45287, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (197, '个', 45241, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (198, '个', 45252, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (199, '个', 45301, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (200, '个', 45302, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (201, '个', 45303, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (202, '个', 45305, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (203, '个', 45227, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (204, '个', 45253, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (205, '个', 45262, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (206, '个', 45263, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (207, '个', 45224, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (208, '个', 45251, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (209, '个', 45238, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (210, '个', 45230, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (211, '个', 45289, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (212, '个', 45290, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (213, '个', 45291, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (214, '个', 45248, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (215, '个', 45300, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (216, '个', 45299, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (217, '个', 45261, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (218, '个', 45274, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (219, '个', 45275, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (220, '个', 45276, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (221, '个', 45277, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (222, '个', 45279, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (223, '个', 45280, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (224, '个', 45282, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (225, '个', 45283, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (226, '个', 45278, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (227, '个', 45250, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (228, '个', 45249, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (229, '个', 45264, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (230, '个', 45235, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (232, '个', 45234, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (233, '个', 45259, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (234, '个', 45255, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (235, '个', 45256, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (236, '条', 45325, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (237, '条', 45351, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (238, '条', 45341, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (239, '条', 45343, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (240, '条', 45353, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (241, '条', 45364, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (242, '条', 45357, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (243, '条', 45339, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (244, '条', 45338, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (245, '条', 45337, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (246, '条', 45356, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (247, '条', 45328, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (248, '条', 45336, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (249, '条', 45334, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (250, '条', 45322, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (251, '条', 45352, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (252, '条', 45346, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (253, '条', 45348, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (254, '条', 45333, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (255, '条', 45342, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (256, '条', 45345, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (257, '条', 45347, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (258, '个', 45379, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (259, '个', 45378, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (260, '个', 45376, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (261, '个', 45374, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (262, '个', 45372, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (263, '张', 31117, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (264, '块', 31118, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (265, '个', 17600008, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (266, '块', 17600010, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (267, '根', 17600026, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (269, '个', 45097, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (270, '个', 45104, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (271, '个', 45590, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (272, '个', 45107, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (273, '个', 45558, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (274, '根', 45101, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (275, '节', 45103, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (276, '根', 45103, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (277, '个', 44678, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (278, '根', 17600014, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (279, '根', 45100, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (280, '个', 45095, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (281, '个', 45093, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (282, '把', 45109, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (283, '个', 45159, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (284, '根', 45135, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (285, '根', 45163, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (286, '个', 45138, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (287, '根', 45155, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (288, '根', 45132, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (289, '根', 45592, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (290, '颗', 45141, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (291, '个', 45158, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (292, '根', 45151, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (293, '个', 45153, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (294, '根', 45152, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (295, '颗', 45142, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (296, '根', 45140, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (297, '个', 45130, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (298, '颗', 45599, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (299, '个', 45144, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (300, '根', 45156, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (301, '根', 45161, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (302, '个', 45136, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (303, '捆', 45168, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (304, '颗', 45165, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (305, '把', 45190, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (306, '颗', 45194, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (307, '颗', 45593, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (308, '颗', 45600, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (309, '颗', 45187, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (310, '颗', 45185, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (311, '捆', 45173, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (312, '盒', 45598, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (313, '个', 45170, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (314, '个', 17600015, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (315, '个', 45112, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (316, '个', 45583, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (317, '个', 45566, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (318, '捆', 45121, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (320, '个', 45113, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (321, '根', 45229, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (322, '根', 17600030, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (323, '根', 45413, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (324, '个', 45407, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (325, '根', 45428, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (326, '根', 45427, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (327, '个', 45418, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (328, '个', 45416, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (329, '个', 45425, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (330, '个', 45424, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (331, '个', 45414, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (332, '根', 45408, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (333, '个', 45423, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (334, '个', 45421, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (335, '个', 45409, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (336, '个', 45417, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (337, '个', 45415, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (338, '个', 45449, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (339, '个', 45441, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (340, '根', 45445, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (341, '个', 45444, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (342, '个', 45450, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (343, '个', 45443, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (344, '个', 45440, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (345, '个', 45455, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (346, '个', 45454, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (347, '个', 45468, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (348, '个', 45466, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (349, '根', 45464, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (350, '个', 45471, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (351, '个', 45467, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (352, '个', 45465, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (353, '根', 45469, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (354, '根', 45463, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (355, '个', 45456, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (356, '只', 45505, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (357, '只', 45500, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (358, '个', 45482, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (359, '只', 45502, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (360, '只', 45501, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (361, '个', 45480, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (362, '个', 45487, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (363, '个', 45488, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (365, '个', 45492, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (366, '个', 45478, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (367, '个', 45479, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (368, '个', 45486, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (369, '个', 45490, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (370, '个', 45481, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (371, '个', 45489, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (372, '个', 45477, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (373, '个', 45484, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (374, '只', 45476, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (375, '只', 45498, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (376, '只', 45473, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (377, '只', 45499, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (378, '个', 45494, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (379, '个', 45495, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (380, '个', 45497, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (381, '个', 45496, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (382, '个', 45475, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (383, '个', 45511, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (384, '个', 45506, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (385, '个', 45510, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (386, '个', 45508, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (387, '个', 45509, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (388, '个', 45514, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (389, '袋', 17600078, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (390, '袋', 17600077, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (391, '个', 17600065, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (393, '捆', 45128, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (394, '捆', 45114, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (397, '盒', 45219, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (398, '盒', 45222, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (400, '个', 17600114, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (401, '个', 17600115, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (402, '颗', 17600116, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (403, '袋', 45096, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (404, '包', 45094, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (405, '包', 45104, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (406, '包', 45590, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (407, '包', 45101, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (408, '袋', 44678, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (409, '袋', 17600014, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (410, '袋', 45093, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (411, '袋', 45112, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (412, '捆', 45127, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (413, '袋', 17600012, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (414, '袋', 45113, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (415, '个', 45171, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (418, '件', 17600130, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (419, '件', 17600146, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (423, '箱', 1561, NULL, '10', NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (424, '箱', 1387, NULL, '10', NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (427, '颗', 100470, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (428, '捆', 100003, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (429, '颗', 100007, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (430, '颗', 102044, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (431, '颗', 100547, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (433, '根', 101874, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (436, '捆', 100005, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (437, '颗', 100008, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (438, '串', 102228, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (439, '根', 102242, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (441, '只', 102248, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (442, '只', 102249, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (443, '袋', 102275, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (445, '根', 102304, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (446, '只', 102306, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (447, '件', 102334, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (448, '包', 100131, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (450, '条', 100393, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (451, '个', 100106, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (452, '把', 101820, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (453, '把', 100545, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (454, '件', 101987, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (455, '节', 100039, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (458, '条', 100077, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (459, '个', 100181, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (460, '个', 100041, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (461, '把', 100704, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (462, '颗', 100011, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (463, '颗', 101837, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (464, '个', 100137, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (465, '颗', 101966, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (466, '颗', 100010, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (468, '包', 101726, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (469, '件', 100926, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (470, '件', 100925, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (471, '件', 100101, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (472, '件', 100985, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (474, '把', 100369, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (475, '个', 101336, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `nx_standard` (`nx_standard_id`, `nx_standard_name`, `nx_s_goods_id`, `nx_standard_file_path`, `nx_standard_scale`, `nx_standard_error`, `nx_standard_sort`, `nx_standard_weight`) VALUES (476, '颗', 102350, NULL, NULL, NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
